### ISSUE TITLE
이미지 워터마크 처리 관련 버그 해결

### ISSUE THREAD

**Issue by janeljs** [TeamTukTalk/tuktalk-backend#94]
```
org.springframework.web.multipart.MultipartException: Current request is not a multipart request
	at org.springframework.web.method.annotation.RequestParamMethodArgumentResolver.handleMissingValueInternal(RequestParamMethodArgumentResolver.java:210) ~[spring-web-5.3.10.jar:5.3.10]
	at org.springframework.web.method.annotation.RequestParamMethodArgumentResolver.handleMissingValue(RequestParamMethodArgumentResolver.java:193) ~[spring-web-5.3.10.jar:5.3.10]
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:114) ~[spring-web-5.3.10.jar:5.3.10]
	at 
```

**Comment by janeljs** [comment]
https://stackoverflow.com/questions/30738574/filenotfoundexception-while-uploading-multi-part-file-spring-boot

**Comment by janeljs** [comment]
![image](https://user-images.githubusercontent.com/68000537/143025321-09c53a25-feae-4398-8c69-aaa05121041a.png)
일단 구현
